/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package student_enrollment_system_nerosa;
import java.util.List;
/**
 *
 * @author FernanCarl
 */
public class EnrollStudentFrame extends javax.swing.JFrame {
    
    private EnrollmentGUI GUI;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EnrollStudentFrame.class.getName());

    /**
     * Creates new form EnrollStudentFrame
     */
    public EnrollStudentFrame(EnrollmentGUI GUI) {
        initComponents();
        this.GUI = GUI;
        loadComboBoxData();
    }

    public EnrollStudentFrame() {
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        FNameLabel = new javax.swing.JLabel();
        NameCBox = new javax.swing.JComboBox<>();
        LNameLabel = new javax.swing.JLabel();
        CourseCBox = new javax.swing.JComboBox<>();
        addStudentBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        jLabel1.setText("Enroll Student");

        FNameLabel.setFont(new java.awt.Font("Sans Serif Collection", 0, 14)); // NOI18N
        FNameLabel.setText("Student Name:");

        NameCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        LNameLabel.setFont(new java.awt.Font("Sans Serif Collection", 0, 14)); // NOI18N
        LNameLabel.setText("Course Name:");

        CourseCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        addStudentBtn.setText("Enroll Student");
        addStudentBtn.addActionListener(this::addStudentBtnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addStudentBtn)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(144, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FNameLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LNameLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(NameCBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CourseCBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(143, 143, 143))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FNameLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(NameCBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LNameLabel)
                    .addComponent(CourseCBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addComponent(addStudentBtn)
                .addGap(49, 49, 49))
        );

        setSize(new java.awt.Dimension(610, 360));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addStudentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentBtnActionPerformed
        
    try {
            String selectedStudent = (String) NameCBox.getSelectedItem();
            String selectedCourse = (String) CourseCBox.getSelectedItem();
            int studentId = Integer.parseInt(selectedStudent.split(" ")[0]);
            int courseId = Integer.parseInt(selectedCourse.split(" ")[0]);
            
            EnrollmentDAO dao = new EnrollmentDAO();
            dao.addEnrollment(studentId, courseId);
            
            if (this.GUI != null) {
                this.GUI.refreshTable();
            }
            this.dispose();
            
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: Could not enroll student. Please check your selections.");
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_addStudentBtnActionPerformed

    private void loadComboBoxData() {
        NameCBox.removeAllItems();
        CourseCBox.removeAllItems();
        
        try {
            
            StudentDAO studentDao = new StudentDAO();
            List<Student> studentList = studentDao.getAllStudents();
            
            for (Student s : studentList) {
                NameCBox.addItem(s.getStudentid() + " - " + s.getFname() + " " + s.getLname());
            }
            
            CoursesDAO courseDao = new CoursesDAO();
            List<Courses> courseList = courseDao.getAllCourses();
            
            for (Courses c : courseList) {
                CourseCBox.addItem(c.getCourseid() + " - " + c.getCourseName());
            }
            
        } catch (Exception e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Error loading data for dropdowns.");
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EnrollStudentFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CourseCBox;
    private javax.swing.JLabel FNameLabel;
    private javax.swing.JLabel LNameLabel;
    private javax.swing.JComboBox<String> NameCBox;
    private javax.swing.JButton addStudentBtn;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
