/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package student_enrollment_system_nerosa;

import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author FernanCarl
 */
public class StudentGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StudentGUI.class.getName());

    /**
     * Creates new form GUI
     */
    public StudentGUI() {
        initComponents();
        refreshTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        addStudentBtn = new javax.swing.JButton();
        updateStudentBtn = new javax.swing.JButton();
        delStudentBtn = new javax.swing.JButton();
        coursesBtn = new javax.swing.JButton();
        EnrollmentBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Management");
        setResizable(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Student ID", "First Name", "Last Name", "Age", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
        }

        addStudentBtn.setText("Add Student");
        addStudentBtn.addActionListener(this::addStudentBtnActionPerformed);

        updateStudentBtn.setText("Update Student");
        updateStudentBtn.addActionListener(this::updateStudentBtnActionPerformed);

        delStudentBtn.setText("Delete Student");
        delStudentBtn.addActionListener(this::delStudentBtnActionPerformed);

        coursesBtn.setText("Courses");
        coursesBtn.addActionListener(this::coursesBtnActionPerformed);

        EnrollmentBtn.setText("Enrollment");
        EnrollmentBtn.addActionListener(this::EnrollmentBtnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addStudentBtn)
                        .addGap(18, 18, 18)
                        .addComponent(updateStudentBtn)
                        .addGap(18, 18, 18)
                        .addComponent(delStudentBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 364, Short.MAX_VALUE)
                        .addComponent(coursesBtn)
                        .addGap(18, 18, 18)
                        .addComponent(EnrollmentBtn)))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addStudentBtn)
                    .addComponent(updateStudentBtn)
                    .addComponent(delStudentBtn)
                    .addComponent(EnrollmentBtn)
                    .addComponent(coursesBtn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1000, 850));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addStudentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentBtnActionPerformed
    new AddStudentFrame().setVisible(true);
    }//GEN-LAST:event_addStudentBtnActionPerformed

    private void updateStudentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateStudentBtnActionPerformed
    new UpdateStudentFrame().setVisible(true);        
    }//GEN-LAST:event_updateStudentBtnActionPerformed

    private void delStudentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delStudentBtnActionPerformed
    new DeleteStudentFrame().setVisible(true);        
    }//GEN-LAST:event_delStudentBtnActionPerformed

    private void coursesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coursesBtnActionPerformed
    new CoursesGUI().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_coursesBtnActionPerformed

    private void EnrollmentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnrollmentBtnActionPerformed
    new EnrollmentGUI().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_EnrollmentBtnActionPerformed
    
    public void refreshTable() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
        StudentDAO dao = new StudentDAO();
        List<Student> list = dao.getAllStudents();
        
        if(list != null) {
            for (Student s : list) {
                Object[] row = {
                    s.getStudentid(),
                    s.getFname(),
                    s.getLname(),
                    s.getAge(),
                    s.getEmail()
                };
                model.addRow(row);
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new StudentGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EnrollmentBtn;
    private javax.swing.JButton addStudentBtn;
    private javax.swing.JButton coursesBtn;
    private javax.swing.JButton delStudentBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton updateStudentBtn;
    // End of variables declaration//GEN-END:variables
}
